// Generated by scripts/export-abis.mjs from the deploy build. Do not edit by hand.

/** The Robinhood Chain mainnet deployment, from contracts/deployments/4663.json. */
export const DEPLOYMENT_4663 = {
  "chainId": 4663,
  "deployer": "0xe23e8C58371468A98206f07b571cF7E6194abBc1",
  "commit": "ca795fff0df26e7c0ac7ab77365a0d4a697a80f3",
  "firstBlock": 79338287,
  "contracts": {
    "SleeveTrade": {
      "address": "0x3757964A25C94040e81a215Dd85B748f6bB9ca84",
      "txHash": "0x4e1da474c95b5912eb207a15820b3913becf18c9deef2178cc5cf928d09fe767",
      "blockNumber": 79338303
    },
    "SleeveBuy": {
      "address": "0xDF3e060D64086ec3309265Ce83B34813eE45F81A",
      "txHash": "0x9d78c42e7429e3e4a3d136cf30361eca3790df98deb8848c82dab575c0c1ee62",
      "blockNumber": 79338287
    },
    "SleeveSell": {
      "address": "0xC0003635086E51aC0c19c40c193043D58d86c987",
      "txHash": "0xd0f69cf54006d31db7eb75f22f43879a6bb2547102c2f401be28b68f7544c22e",
      "blockNumber": 79338318
    },
    "SleeveTimelock": {
      "address": "0x0088C481C56b7B2407C6a981BAc3da0CC0Fc5b2D",
      "txHash": "0x26c8388e857c546b323010c821324c20f5700316434eba96c6a3c0536d1e5693",
      "blockNumber": 79338331
    },
    "SessionCalendarExtension": {
      "address": "0xa7a3C55309E5FB2Fb61eeA6F6e2318CF927b247D",
      "txHash": "0x9edae2995f7f560b8c8198ee311fe7a50cbe5d3ea2400415cc06065823772e8c",
      "blockNumber": 79338344
    },
    "TokenSource": {
      "address": "0x6643a2F99534c90a68E6eCE707c7bFA6D5b0975F",
      "txHash": "0x3207b109626c24dda48236a51f0d94b22f7eab0e0751278f35594ccb8ea6ee83",
      "blockNumber": 79338357
    },
    "SleeveModule": {
      "address": "0x15FA6775fCdB5904aA673967461dc1fA3c6E7Ac9",
      "txHash": "0x38523e1061dd33658cab2bbf98a4a8514dcb30a17c33ced08fbaf49a9cc58107",
      "blockNumber": 79338373
    }
  }
} as const;
