import path from 'node:path';

import { tokenLogo, type LogoKey } from '@/components/token/registry';
import { CARD_FONTS, type CardFontFile } from '@/generated/card-fonts';
import { TOKEN_LOGOS, type TokenLogoPath } from '@/generated/token-logos';

import { CARD_FONT_FAMILY } from '../card-env';

/**
 * Server only. The two families docs/DESIGN.md section 4 sets, as the static TrueType instances Google Fonts serves
 * (Satori reads ttf, otf and woff, not woff2), and the token logos from public/assets/tokens as data URIs. Both are
 * embedded in src/generated by scripts/embed-server-assets.mjs, so drawing an image reads no file at run time
 * (D-033). The licenses sit beside the fonts in ../fonts.
 */

type FontWeight = 400 | 500 | 600;

export interface ImageFont {
  name: string;
  data: Buffer;
  weight: FontWeight;
  style: 'normal';
}

function font(name: string, weight: FontWeight, file: CardFontFile): ImageFont {
  return { name, data: Buffer.from(CARD_FONTS[file], 'base64'), weight, style: 'normal' };
}

let fonts: ImageFont[] | null = null;

export function imageFonts(): ImageFont[] {
  fonts ??= [
    font(CARD_FONT_FAMILY.sans, 400, 'InstrumentSans-Regular.ttf'),
    font(CARD_FONT_FAMILY.sans, 500, 'InstrumentSans-Medium.ttf'),
    font(CARD_FONT_FAMILY.sans, 600, 'InstrumentSans-SemiBold.ttf'),
    font(CARD_FONT_FAMILY.mono, 400, 'IBMPlexMono-Regular.ttf'),
    font(CARD_FONT_FAMILY.mono, 500, 'IBMPlexMono-Medium.ttf'),
  ];
  return fonts;
}

const logos = new Map<LogoKey, string>();

const IMAGE_TYPES: Record<string, string> = { '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml' };

function isEmbeddedLogo(src: string): src is TokenLogoPath {
  return Object.hasOwn(TOKEN_LOGOS, src);
}

/** The token's committed logo file, the one TokenIcon shows, inlined so the renderer never fetches anything. */
export function logoDataUri(key: LogoKey): string {
  const known = logos.get(key);
  if (known !== undefined) return known;
  const logo = tokenLogo(key);
  const type = IMAGE_TYPES[path.extname(logo.src).toLowerCase()];
  if (type === undefined) throw new Error(`The image renderer cannot draw ${logo.src}`);
  if (!isEmbeddedLogo(logo.src)) throw new Error(`${logo.src} is not embedded; run node scripts/embed-server-assets.mjs`);
  const uri = `data:${type};base64,${TOKEN_LOGOS[logo.src]}`;
  logos.set(key, uri);
  return uri;
}
