#!/usr/bin/env node
// Writes packages/core/src/contracts/{abis,deployment}.ts from the deploy build and contracts/deployments/4663.json,
// so the app, keeper and verifier read one copy of every ABI and address. Run after a deploy:
//   cd contracts && FOUNDRY_OUT=out-deploy forge build && cd .. && node scripts/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'contracts', process.env.FOUNDRY_OUT ?? 'out-deploy');
const target = join(root, 'packages', 'core', 'src', 'contracts');

function abiOf(file, name) {
  return JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8')).abi;
}

function signature(item) {
  const types = (item.inputs ?? []).map((input) => input.type).join(',');
  return `${item.type}:${item.name ?? ''}(${types})`;
}

// Calls into the module run its external libraries by delegatecall, so their events and errors come from the
// module's address. Decoding them needs the module's ABI plus every event and error the libraries declare.
function moduleAbi() {
  const merged = new Map();
  for (const item of abiOf('SleeveModule.sol', 'SleeveModule')) merged.set(signature(item), item);
  for (const [file, name] of [
    ['SleeveTrade.sol', 'SleeveTrade'],
    ['SleeveBuy.sol', 'SleeveBuy'],
    ['SleeveSell.sol', 'SleeveSell'],
  ]) {
    for (const item of abiOf(file, name)) {
      if (item.type !== 'event' && item.type !== 'error') continue;
      if (!merged.has(signature(item))) merged.set(signature(item), item);
    }
  }
  return [...merged.values()];
}

const abis = {
  sleeveModuleAbi: moduleAbi(),
  tokenSourceAbi: abiOf('TokenSource.sol', 'TokenSource'),
  sessionCalendarExtensionAbi: abiOf('SessionCalendarExtension.sol', 'SessionCalendarExtension'),
  sleeveTimelockAbi: abiOf('SleeveTimelock.sol', 'SleeveTimelock'),
  stockTokenAbi: abiOf('IStockToken.sol', 'IStockToken'),
  accessControlsRegistryAbi: abiOf('IAccessControlsRegistry.sol', 'IAccessControlsRegistry'),
  aggregatorV3Abi: abiOf('IAggregatorV3.sol', 'IAggregatorV3'),
  uniswapV3PoolAbi: abiOf('IUniswapV3Pool.sol', 'IUniswapV3Pool'),
  quoterV2Abi: abiOf('IQuoterV2.sol', 'IQuoterV2'),
  swapRouter02Abi: abiOf('ISwapRouter02.sol', 'ISwapRouter02'),
  erc20Abi: abiOf('IERC20Metadata.sol', 'IERC20Metadata'),
};

const header = '// Generated by scripts/export-abis.mjs from the deploy build. Do not edit by hand.\n';
let abiFile = header;
for (const [name, abi] of Object.entries(abis)) {
  abiFile += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

const record = JSON.parse(readFileSync(join(root, 'contracts', 'deployments', '4663.json'), 'utf8'));
const contracts = Object.fromEntries(
  Object.entries(record.contracts).map(([name, entry]) => [
    name,
    { address: entry.address, txHash: entry.txHash, blockNumber: entry.blockNumber },
  ]),
);
const firstBlock = Math.min(...Object.values(record.contracts).map((entry) => entry.blockNumber));
const deploymentFile =
  header +
  `\n/** The Robinhood Chain mainnet deployment, from contracts/deployments/4663.json. */\n` +
  `export const DEPLOYMENT_4663 = ${JSON.stringify(
    {
      chainId: record.chainId,
      deployer: record.deployer,
      commit: record.source.commit,
      firstBlock,
      contracts,
    },
    null,
    2,
  )} as const;\n`;

mkdirSync(target, { recursive: true });
writeFileSync(join(target, 'abis.ts'), abiFile);
writeFileSync(join(target, 'deployment.ts'), deploymentFile);
console.log(`wrote ${Object.keys(abis).length} ABIs and ${Object.keys(contracts).length} addresses to ${target}`);
