"""docs/HP2_RESULTS.md from the summary JSON, through TEMPLATE. Every figure comes from the summary, so
scripts/hp2/run.py --report-only rebuilds the report from results/hp2/summary.json alone."""

from string import Template

SCOPE_NAMES = {"pooled": "Pooled"}
POLICY_NAMES = {"arrival": "Arrival", "guarded": "Guarded", "calendar_only": "Calendar only"}
REFERENCE_NAMES = {"primary": "primary reference", "secondary": "secondary reference"}
REASON_ORDER = ("SESSION", "STALE", "MULTIPLIER", "DEPEG", "PAUSED", "ORACLE_PAUSED", "NO_QUOTE", "PREMIUM")

TEMPLATE = Template("""\
# HP2 replay results

$status

Written by scripts/hp2/run.py from results/hp2/summary.json, under the protocol pre-registered in \
docs/HP2_PROTOCOL.md (sha256 $protocol_sha). Do not edit this file by hand. Rerun the script.

## Verdict

$verdict_line

| Rule | Figure | Holds |
| --- | --- | --- |
| Pooled mean of arrival premium minus guarded premium is above zero | $mean_difference bps | $above_zero |
| Its 95 percent bootstrap interval excludes zero | $interval bps | $excludes_zero |
| Guarded median delay is at most 72 hours | $median_delay hours | $delay_ok |

The cut is the protocol's: all $payments payments pooled, 100 USDG, primary reference, $resamples bootstrap \
resamples from seed $bootstrap_seed.

### What the pooled mean is made of

$drivers

### The same rule on the other cuts

For information only. The verdict above is the pre-registered one.

$other_cuts

## Premiums

Policy columns give the mean and the median premium in basis points over the market reference. Difference columns \
give the paired mean difference in basis points with its 95 percent bootstrap interval. A positive difference means \
the guarded policy paid less.

$premium_tables

## Delay

Delay runs from the arrival to the fill. A payment waited when its fill came after its arrival instant.

$delay_tables

## Counts

$counts_table

Off-hours arrivals are payments that arrived while the module's calendar said the session was closed. An arrival \
fallback is a payment whose arrival quote reverted at every allowlisted pool, so the arrival policy bought at the \
first later evaluation instant with a working quote. Evaluated instants with no quote count every instant some \
payment was evaluated at while every pool reverted. Reverted quote calls count every reverted QuoterV2 call in the \
fetched data. Dropped rounds are the feed rounds the protocol drops for an answer above 10 times the feed's median.

## Why the guarded policy waited

The first failing check at each instant the guarded policy did not buy, summed over payments, in the module's \
check order.

$wait_tables

## Data notes

$data_notes

## Checks

$checks

## Session calendar

$calendar

## Providers

$providers

## Provider rerun

$rerun

## Readings of the protocol

Where the protocol leaves a detail open, the engine reads it as follows. None of these changes a definition.

$readings

## Files and how to reproduce

$files

Reproduce from the repo root with the virtualenv in scripts/hp2/.venv:

```
scripts/hp2/.venv/bin/python scripts/hp2/run.py
scripts/hp2/.venv/bin/python scripts/hp2/run.py --report-only
cd scripts && hp2/.venv/bin/python -m unittest discover -s hp2/tests -t .
```

The first command reads results/hp2/data only and makes no network call. The session test runs the compiled \
SessionCalendar through forge, from answers cached by source hash, and the Python port checks every instant.
""")


def count(n: int) -> str:
    return f"{n:,}"


def bps(value: float) -> str:
    return f"{value:,.2f}"


def hours(value: float) -> str:
    return f"{value:,.2f}"


def interval(pair) -> str:
    return f"{bps(pair[0])} to {bps(pair[1])}"


def yes(value: bool) -> str:
    return "yes" if value else "no"


def scope_name(scope: str) -> str:
    return SCOPE_NAMES.get(scope, scope)


def table(header: list[str], rows: list[list[str]], align: list[str] | None = None) -> str:
    align = align or ["---"] * len(header)
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(align) + " |"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def _status(summary: dict) -> str:
    status = summary["status"]
    if not status["provisional"]:
        return (
            "Final. The session test ran on the compiled SessionCalendar through forge, and the provider rerun was "
            "compared row by row."
        )
    lines = ["PROVISIONAL. These figures can still change, for these reasons:", ""]
    lines += [f"- {reason}" for reason in status["reasons"]]
    return "\n".join(lines)


def _drivers(verdict: dict) -> str:
    d = verdict["drivers"]
    fb, above, within = d["arrival_fallbacks"], d["arrival_above_cap"], d["arrival_within_cap"]
    payments = sum(part["payments"] for part in d["by_ticker"].values())
    shares = ", ".join(f"{t} {bps(part['contribution_bps'])}" for t, part in d["by_ticker"].items())
    lines = [
        (
            f"Each payment adds its difference divided by {count(payments)} to the pooled mean of "
            f"{bps(verdict['mean_difference_bps'])} bps. Added up by ticker, in bps: {shares}."
        )
    ]
    if fb["payments"]:
        fills = ", ".join(f"{count(n)} at {at}" for at, n in fb["arrival_fills_at"].items())
        lines.append(
            f"{count(fb['payments'])} payments are arrival fallbacks, which the arrival policy bought at the first "
            f"later instant with a working quote ({fills}). They add {bps(fb['contribution_bps'])} bps."
        )
    lines.append(
        f"{count(above['payments'])} payments had an arrival fill more than the guard's {above['cap_bps']} bps cap "
        f"above the reference, {count(above['arrival_fallbacks_among_them'])} of them arrival fallbacks. They add "
        f"{bps(above['contribution_bps'])} bps. The other {count(within['payments'])} payments add "
        f"{bps(within['contribution_bps'])} bps"
        + (f", a mean difference of {bps(within['mean_bps'])} bps each." if within["payments"] else ".")
    )
    lines.append("Where the guarded policy gained most:\n\n" + _difference_table(d["largest_for_guarded"]))
    lines.append("Where it lost most:\n\n" + _difference_table(d["largest_against_guarded"]))
    return "\n\n".join(lines)


def _difference_table(groups: list[dict]) -> str:
    """Payments that bought at the same instants under both policies share a row."""
    rows = []
    for g in groups:
        first, last = g["first_arrival_iso"][:19] + "Z", g["last_arrival_iso"][:19] + "Z"
        arrived = first if len(g["payments"]) == 1 else f"{first} to {last}"
        rows.append(
            [
                g["ticker"],
                count(len(g["payments"])),
                arrived,
                g["arrival_fill_iso"],
                g["guarded_fill_iso"],
                bps(g["arrival_premium_bps"]),
                bps(g["guarded_premium_bps"]),
                bps(g["difference_bps"]),
            ]
        )
    header = ["Ticker", "Payments", "Arrived", "Arrival bought", "Guarded bought", "Arrival", "Guarded", "Difference"]
    return table(header, rows, ["---", "---:", "---", "---", "---", "---:", "---:", "---:"])


def _other_cuts(verdict: dict) -> str:
    rows = [
        [
            f"{count(cut['size_usdg'])} USDG",
            REFERENCE_NAMES[cut["reference"]],
            bps(cut["mean_difference_bps"]),
            interval(cut["ci95_bps"]),
            hours(cut["guarded_median_delay_hours"]),
            cut["outcome"],
        ]
        for cut in verdict["same_rule_on_other_cuts"]
    ]
    header = ["Size", "Reference", "Mean difference, bps", "95% interval, bps", "Guarded median delay, h", "Rule gives"]
    return table(header, rows, ["---", "---", "---:", "---", "---:", "---"])


def _premium_tables(summary: dict) -> str:
    parts = []
    for size, by_reference in summary["premiums"].items():
        for ref, by_scope in by_reference.items():
            rows = []
            for scope, block in by_scope.items():
                cells = [scope_name(scope), count(block["payments"])]
                for policy in POLICY_NAMES:
                    p = block["policies"][policy]
                    cells.append(f"{bps(p['mean_bps'])} / {bps(p['median_bps'])}")
                for name in ("arrival_minus_guarded", "calendar_only_minus_guarded"):
                    diff = block["differences"][name]
                    cells.append(f"{bps(diff['mean_bps'])} ({interval(diff['ci95_bps'])})")
                rows.append(cells)
            header = [
                "Scope",
                "Payments",
                "Arrival",
                "Guarded",
                "Calendar only",
                "Arrival minus guarded",
                "Calendar only minus guarded",
            ]
            align = ["---", "---:", "---:", "---:", "---:", "---", "---"]
            parts.append(f"### {count(int(size))} USDG, {REFERENCE_NAMES[ref]}\n\n" + table(header, rows, align))
    return "\n\n".join(parts)


def _delay_tables(summary: dict) -> str:
    parts = []
    for size, by_scope in summary["delays"].items():
        rows = []
        for scope, policies in by_scope.items():
            g, c = policies["guarded"], policies["calendar_only"]
            rows.append(
                [
                    scope_name(scope),
                    hours(g["median_hours"]),
                    hours(g["p90_hours"]),
                    hours(g["mean_hours"]),
                    hours(g["max_hours"]),
                    f"{count(g['waited'])} ({g['waited_share'] * 100:.1f}%)",
                    hours(c["median_hours"]),
                    hours(c["p90_hours"]),
                    f"{count(c['waited'])} ({c['waited_share'] * 100:.1f}%)",
                ]
            )
        header = [
            "Scope",
            "Guarded median, h",
            "Guarded p90, h",
            "Guarded mean, h",
            "Guarded max, h",
            "Guarded waited",
            "Calendar only median, h",
            "Calendar only p90, h",
            "Calendar only waited",
        ]
        align = ["---"] + ["---:"] * 8
        parts.append(f"### {count(int(size))} USDG\n\n" + table(header, rows, align))
    return "\n\n".join(parts)


def _counts_table(summary: dict) -> str:
    sizes = [str(s) for s in summary["inputs"]["sizes_usdg"]]
    notes = summary["data_notes"]
    reverts = notes["reverted_quote_calls_in_data"]
    dropped = notes["dropped_rounds"]
    stock = [scope for scope in summary["counts"] if scope != "pooled"]
    rows = []
    for scope, c in summary["counts"].items():
        tickers = stock if scope == "pooled" else [scope]
        revert_calls = reverts["total"] if scope == "pooled" else reverts["by_ticker"].get(scope, 0)
        dropped_rounds = sum(dropped[t]["dropped"] for t in tickers)
        rows.append(
            [
                scope_name(scope),
                count(c["payments"]),
                count(c["off_hours_arrivals"]),
                " / ".join(count(c["arrival_fallbacks"][s]) for s in sizes),
                " / ".join(count(c["evaluated_instants_without_quote"][s]) for s in sizes),
                count(revert_calls),
                count(dropped_rounds),
            ]
        )
    size_label = " / ".join(f"{count(int(s))}" for s in sizes)
    header = [
        "Scope",
        "Payments",
        "Off-hours arrivals",
        f"Arrival fallbacks ({size_label} USDG)",
        f"Evaluated instants with no quote ({size_label} USDG)",
        "Reverted quote calls in the data",
        "Dropped rounds",
    ]
    usdg = dropped["USDG/USD"]["dropped"]
    return table(header, rows, ["---"] + ["---:"] * 6) + f"\n\nThe USDG/USD feed has {count(usdg)} dropped rounds."


def _wait_tables(summary: dict) -> str:
    parts = []
    for size, by_scope in summary["guard_wait_reasons"].items():
        reasons = [r for r in REASON_ORDER if any(r in counts for counts in by_scope.values())]
        rows = [[scope_name(scope)] + [count(counts.get(r, 0)) for r in reasons] for scope, counts in by_scope.items()]
        parts.append(
            f"### {count(int(size))} USDG\n\n" + table(["Scope", *reasons], rows, ["---"] + ["---:"] * len(reasons))
        )
    return "\n\n".join(parts)


def _data_notes(summary: dict) -> str:
    notes = summary["data_notes"]
    lines = []
    windows = summary["inputs"]["windows"]
    spans = ", ".join(f"{t} {w['start_iso']} to {w['end_iso']}" for t, w in windows.items())
    lines.append(
        f"- Windows run from 24 hours after the creation of each ticker's fee-500 pool to 96 hours before end block "
        f"{count(summary['inputs']['end_block'])} ({summary['inputs']['end_block_iso']}): {spans}."
    )
    for o in notes["pool_outages"]:
        between = "none" if o["working_quotes_between"] == 0 else count(o["working_quotes_between"])
        text = (
            f"- {o['ticker']} fee-{o['fee']} pool {o['pool']}: every quote reverted at the "
            f"{count(o['quoted_blocks_reverted'])} blocks quoted from {o['first_revert_iso']} to "
            f"{o['last_revert_iso']}, and {between} of its quotes in between worked."
        )
        if o["first_working_after_iso"]:
            shown = [
                f"{count(int(size))} USDG ran to the price limit"
                if premium is None
                else f"{count(int(size))} USDG paid {bps(premium)} bps over the round in force"
                for size, premium in o["first_working_after_premium_bps"].items()
            ]
            text += f" At its first working quote after that, {o['first_working_after_iso']}, {' and '.join(shown)}."
        lines.append(text)
    for p in notes["quotes_at_price_limit"]:
        lines.append(
            f"- {count(p['quotes_at_price_limit'])} {p['ticker']} fee-{p['fee']} quotes for "
            f"{count(p['usdg_in'])} USDG, from {p['first_iso']} to {p['last_iso']}, ran to the swap's price limit: the "
            "pool could not take the "
            "whole payment. The run stops if such a quote is ever the best one at an instant it evaluates, so none "
            "priced a fill."
        )
    for m in notes["multiplier_changes"]:
        lines.append(
            f"- {m['ticker']} multiplier change scheduled at {m['scheduled_iso']}, effective {m['effective_iso']}, "
            f"from {int(m['old']) / 1e18:.6f} to {int(m['new']) / 1e18:.6f}."
        )
    dropped = ", ".join(
        f"{name} {d['dropped']}" + (f" (last {d['last_dropped_iso']})" if d["last_dropped_iso"] else "")
        for name, d in notes["dropped_rounds"].items()
    )
    when = "All of them predate" if notes["dropped_rounds_all_before_the_windows"] else "Some of them fall inside"
    lines.append(f"- Dropped rounds per feed: {dropped}. {when} every window.")
    for size, u in summary["usdg_at_fills"].items():
        lines.append(
            f"- USDG/USD at the {count(int(size))} USDG fills: answers {u['min_answer'] / 1e8:.8f} to "
            f"{u['max_answer'] / 1e8:.8f}, at most {hours(u['max_age_hours'])} hours old. Premiums value USDG at 1 USD."
        )
    return "\n".join(lines)


def _checks(summary: dict) -> str:
    c = summary["checks"]
    opening = c["rounds_updated_at_an_opening_instant"]
    lines = [
        (
            f"- At all {count(c['evaluations_checked_round_in_force_by_block'])} evaluations, the round in force by "
            "updated_at equals the round in force by the transmit block from the AnswerUpdated logs, for the ticker's "
            "feed and USDG/USD, and every arrival was evaluated at the block arrivals.json records for it."
        ),
        (
            f"- {count(len(opening))} rounds were updated exactly at a session's opening second, so reading a fresh "
            "round as at or after the opening instant, rather than strictly after it, "
            + ("changed nothing." if not opening else "matters for those rounds.")
        ),
        (
            f"- The last pause event on any token or the registry was at {c['last_pause_event_iso']}, before the "
            f"first evaluated instant {c['first_evaluated_instant_iso']}, so no evaluation depends on how pauses are "
            "read."
        ),
    ]
    return "\n".join(lines)


def _calendar(summary: dict) -> str:
    c = summary["calendar"]
    text = f"The session test used {c['oracle']}."
    if "instants_checked_against_port" in c:
        sources = c["forge_sources_sha256"]
        text += (
            f" {count(c['instants_answered'])} instants were answered and the Python port agreed on all "
            f"{count(c['instants_checked_against_port'])} of them. Forge ran {c['forge_runs_this_run']} times in this "
            "run, and every answer it did not compute came from results/hp2/cache/session, which is keyed by the "
            "sha256 of the library "
            f"({sources['library'][:16]}), the oracle script ({sources['script'][:16]}) and foundry.toml "
            f"({sources['foundry_toml'][:16]})."
        )
    else:
        text += f" {count(c['instants_answered'])} instants were answered by the Python port alone."
    if c["provisional_reason"]:
        text += f" {c['provisional_reason']}"
    return text + f" Python port sha256: {c['port_sha256'][:16]}."


def _providers(summary: dict) -> str:
    p = summary["providers"]
    return (
        f"Quotes came from {p['archive_rpc']} (QuoterV2 eth_call at each instant's block). Logs, feed rounds and "
        f"block headers came from {p['public_rpc']}, in {p['fetch_runs']} fetch runs under the cache profile "
        f"{p['profile']}. The protocol's Data section names the keeper's provider for historical logs, which is dRPC "
        "until the Alchemy app exists, so the logs here came from another endpoint than the one it names. Logs are "
        "final on any endpoint, and every kept round matched its AnswerUpdated log (results/hp2/data/checks.json). "
        "The rerun on the keeper's provider is compared row by row with run.py --provider-rerun."
    )


def _rerun(summary: dict) -> str:
    rerun = summary.get("provider_rerun")
    if not rerun:
        return "Not done yet."
    diffs = rerun["differences"]
    text = f"{count(rerun['rows_compared'])} rows compared with {rerun['rerun_dir']}: {count(len(diffs))} differences."
    if diffs:
        rows = [
            [count(d["size_usdg"]), " ".join(map(str, d["key"])), d["field"], d.get("ours", ""), d.get("theirs", "")]
            for d in diffs[:50]
        ]
        text += "\n\n" + table(["Size", "Payment and policy", "Field", "This run", "Rerun"], rows)
        if len(diffs) > 50:
            text += f"\n\nThe first 50 of {count(len(diffs))} are shown. summary.json lists all of them."
    return text


def _readings(summary: dict) -> str:
    return "\n".join(f"{n}. {r['topic']}. {r['reading']}" for n, r in enumerate(summary["readings"], 1))


def _files(summary: dict) -> str:
    lines = []
    for name, rows in summary["outputs"].items():
        what = "one row per payment per policy" if name.startswith("rows") else "one row per payment per evaluation"
        lines.append(f"- results/hp2/{name}: {count(rows)} rows, {what}.")
    lines.append("- results/hp2/summary.json: every figure in this report, and the inputs' sha256.")
    return "\n".join(lines)


def render(summary: dict) -> str:
    v = summary["verdict"]
    inputs = summary["inputs"]
    label = "Provisional verdict" if summary["status"]["provisional"] else "Verdict"
    return TEMPLATE.substitute(
        status=_status(summary),
        protocol_sha=summary["protocol"]["sha256"][:16],
        verdict_line=f"{label}: {v['outcome']}.",
        mean_difference=bps(v["mean_difference_bps"]),
        above_zero=yes(v["conditions"]["mean_difference_above_zero"]),
        interval=interval(v["ci95_bps"]),
        excludes_zero=yes(v["conditions"]["interval_excludes_zero"]),
        median_delay=hours(v["guarded_median_delay_hours"]),
        delay_ok=yes(v["conditions"]["median_delay_at_most_72_hours"]),
        payments=count(summary["counts"]["pooled"]["payments"]),
        resamples=count(inputs["resamples"]),
        bootstrap_seed=inputs["bootstrap_seed"],
        drivers=_drivers(v),
        other_cuts=_other_cuts(v),
        premium_tables=_premium_tables(summary),
        delay_tables=_delay_tables(summary),
        counts_table=_counts_table(summary),
        wait_tables=_wait_tables(summary),
        data_notes=_data_notes(summary),
        checks=_checks(summary),
        calendar=_calendar(summary),
        providers=_providers(summary),
        rerun=_rerun(summary),
        readings=_readings(summary),
        files=_files(summary),
    )
